# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absente', '0003_auto_20180602_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolobject',
            name='color',
            field=models.IntegerField(choices=[(0, '#cc4646'), (1, '#3b91ad'), (2, '#3bcc91')], default=1, help_text='*Note: Curs->#cc4646 Laborator->#3b91ad  Seminar->#3bcc91'),
            preserve_default=False,
        ),
    ]
